- name: creating the bastion host
  hosts: localhost
  become: true
  connection: local
  gather_facts: false
  tasks:
    - name: importing the bastion_setup variables
      include_vars: vars/Bastion_setup

    - name: importing the vcp_setup variables
      include_vars: vars/vpc_setup

    - name: importing the vpc-output.var variables
      include_vars: vars/vpc-output.var

    - name: creating the key pair for aws
      ec2_key:
        name: vprofile-key
        region: "{{region}}"
        state: present
      register: key_out

    - debug:
        var: key_out

    - name:
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./vprofile-key.pem"
        mode: 0600
      when: key_out.changed

    - name: creating the security group for bastion host
      ec2_group:
        name: bastion-sg
        description: allow port 22 from any where
        region: "{{region}}"
        state: present
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
      register: bastionsg_out

    - name: creating the bastion host
      ec2:
        key_name: vprofile-key
        region: "{{region}}"
        state: present
        instance_type: t2.micro
        image: "{{bastion_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: Bastion-host
          project: vprofile
          owner: devopsteam
        exact_count: 1
        count_tag:
          Name: Bastion-host
          project: vprofile
          owner: devopsteam
        group_id: "{{bastionsg_out.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastiohost_out
